version: '3.1'
services:
  local_mysql:
    image: 'mysql'
    container_name: 'local_mysql'
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_DATABASE: 'local'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
      TZ: '+00:00'
    restart: 'unless-stopped'
    ports:
      - '3306:3306'
    volumes:
      - /data/local/mysql:/var/lib/mysql